tasks:
  - name: Init Formbricks
    init: |
      cp .env.example .env &&
      bash .gitpod/init.bash && 
      turbo --filter "@formbricks/js" build && 
      gp sync-done init-install
    command: gp sync-done init && gp tasks list

  - name: db
    init: |
      gp sync-await init-install &&
      turbo --filter "@formbricks/database" go &&
      gp sync-done db-setup-init
    command: |
      gp sync-await init && 
      turbo --filter "@formbricks/database" go &&
      gp sync-done db-started

  - name: web
    init: |
      gp sync-await init-install && 
      bash .gitpod/setup-web.bash &&
      turbo --filter "@formbricks/database" db:down
    command: |
      gp sync-await init && 
      gp sync-await db-started &&
      turbo --filter "@formbricks/web" go

  - name: demo
    init: |
      gp sync-await init-install && 
      bash .gitpod/setup-demo.bash
    command: |
      cd apps/demo && 
      cp .env.example .env &&
      gp sync-await init && 
      turbo --filter "@formbricks/demo" dev

  - name: api
    init: |
      gp sync-await init-install &&
      bash .gitpod/setup-api.bash
    command: |
      gp sync-await init && 
      turbo --filter "@formbricks/api" go

  - name: errors
    command: |
      gp sync-await init && 
      turbo --filter "@formbricks/errors" go

image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 3002
    visibility: public
    onOpen: open-preview
  - port: 5432
    visibility: public
    onOpen: ignore

github:
  prebuilds:
    master: true
    pullRequests: true
    addComment: true

vscode:
  extensions:
    - "ban.spellright"
    - "bradlc.vscode-tailwindcss"
    - "DavidAnson.vscode-markdownlint"
    - "dbaeumer.vscode-eslint"
    - "esbenp.prettier-vscode"
    - "Prisma.prisma"
    - "yzhang.markdown-all-in-one"
